### ISSUE TITLE
Is it possible to create a default HTML report?

### ISSUE THREAD

**Issue by kpassoubady** [sdstoehr/har-reader#16]
Like the one below:
http://www.softwareishard.com/har/viewer/

**Comment by sdstoehr** [comment]
I would like to keep this library focused on providing basic Java classes to access HAR files, because most of the current users use it for exactly this purpose.

A HTML report could be easily developed as a separate project based on this library.
Of course I would add a link to this project once it is available :)

Best,
Sebastian
