### ISSUE TITLE
HarResponse transferSize value.

### ISSUE THREAD

**Issue by adek445** [sdstoehr/har-reader#18]
Hello,
I would like to ask if there's possible to add variable transferSize?
I think it could be useful but I didn't find that value in HarResponse class.

Best regards
Andrew

**Comment by sdstoehr** [comment]
Hi @adek445 

I couldn't find anything about `transferSize` in the HAR spec:
http://www.softwareishard.com/blog/har-12-spec/

Chrome is adding a `_transferSize` property. Because other tools (e.g. WebpageTest.org) add other properties, I decided to go for a generic solution.
In version 2.1.0 (will be available in Maven Central soon) you can access these additional properties in a `Map<String, Object>`. The map contains all properties, which are not defined in the spec.

```java
response.getAdditional().get("_transferSize");
```

I hope that this will work in your scenario.

Best,
Sebastian

**Comment by adek445** [comment]
Thank You Sebastian for your HarResponse :). 
Yes i thought about `_transferSize`. 
So I will wait for 2.1.0 version.

Have a nice day
Andrew
