### ISSUE TITLE
Har Entry un-ordered

### ISSUE THREAD

**Issue by alessandroBalliniGPA** [sdstoehr/har-reader#187]
I have an har with 2 entries

2024-12-20T16:32:53.551**0**37107+01:00 EndPointA
2024-12-20T16:32:53.551**9**91839+01:00 EndPointB

When parsing har the lib endpoints are not correctoly ordered.

EndPointB
EndPointA

**Comment by sdstoehr** [comment]
Hi,

the project uses lists, so that the order of the input file should be kept. I don't see any code, which changes the order of the entries (on purpose or accidentally).

Can you double check the source file? Are the entries already in the 'wrong' order there?

If you need a special sorting (e.g. based on when the requests were initiated), you would need to sort it yourself - or you need to ensure that the tool you are using to generate the HAR is storing it in that order.
I try to keep the library lightweight and the representation should be close to the input to serve as many different needs as possible (maybe someone wants to have the order as in the source file, another one would like to have it ordered differently, ...)

Best,
Sebastian

**Comment by alessandroBalliniGPA** [comment]
The elements in the 'entries' array may be unordered, so it is possible to sort them, for example, by 'startDateTime'. The problem arises when the timestamps are of this type:

2024-12-20T16:32:53.**551**037107+01:00 EndPointA
2024-12-20T16:32:53.**551**991839+01:00 EndPointB

The library, during parsing, uses a java.util.Date which in these cases loses precision because it stops at the millisecond. It is not possible to sort EndpointA and EndpointB because I don't know which one comes first and which one comes after, as they both have the same Date
2024-12-20T16:32:53.551

Is it possible to increase the precision of the startDateTime?

**Comment by sdstoehr** [comment]
Hi,

you can try using version 3.0.0 (should be available through maven central soon), which uses `ZonedDateTime` rather than `Date` and should provide you with everything you need to sort your entries as wished.

_Please note: Version 3.0.0 contains some more breaking changes, as it raises the minimum Java version to 17, makes use of records and gets rid of some deprecated stuff. But most likely you are not impacted by any of these things and changing the getters from `.getPropery()` to `.property()` is all you need to do._

Best,
Sebastian

**Comment by alessandroBalliniGPA** [comment]
Thank you for the quick support. 
The new version works as expected.
